title: Yuxi Chen's Portfolio
description: Data projects and coursework
email: yuxichen11@gmail.com
baseurl: ""
url: "https://ychn01.github.io"

theme: jekyll-theme-cayman

header_pages:
  - index.md
  - projects.md

defaults:
  - scope:
      path: ""
    values:
      robots: noindex, nofollow
